---
title: "Untitled"
author: "Joanna Yeung"
date: "2026-04-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# load in workspace with DESeq results and rlog counts matrix of genes. 
```{r}
load("/lustre/fs4/risc_lab/scratch/jyeung/Manuscript_Figures/Figure2/workspace.RData")
```

# ATAC-seq: import motif enrichment results under ALL up peaks across all timepoint comparisons & drug treatment. 
```{r}
expressedGenes <- LFCResultsall_RNA[[1]]$SYMBOL
expressedGenes[grep("TP53$|TP63$|TP73$", expressedGenes)] <- c("P63", "P73", "P53")
expressedGenes[expressedGenes %in% "RELA"] <- "TF65"
annoUpPeaks_AME_df <- process_motif_data("/lustre/fs4/risc_lab/scratch/jyeung/Manuscript_Figures/FigureS3/motif_analysis_output/DESeq/annoUp", expressed_genes = expressedGenes)

annoUpPeaks_AME_df$Comparison <- gsub("\\..*", "", row.names(annoUpPeaks_AME_df))
annoUpPeaks_AME_df$Comparison <- factor(annoUpPeaks_AME_df$Comparison, levels=unique(annoUpPeaks_AME_df$Comparison)[c(15,1,5,9,2,6,10,16,3,7,11,13,4,8,12,14)]) # column to identify DESeq comparison

annoUpPeaks_AME_df$Group <- ifelse(grepl("DoxovsCycling", annoUpPeaks_AME_df$Comparison), "DoxovsCycling", ifelse(grepl("PalbovsCycling", annoUpPeaks_AME_df$Comparison), "PalbovsCycling", ifelse(grepl("Doxovsday3Doxo", annoUpPeaks_AME_df$Comparison), "Doxovsday3Doxo", "Palbovsday3Palbo"))) # column to identify relative to cycling or day 3 comparison and drug treatment. 

annoUpPeaks_AME_df$Timepoint <-  gsub("(day[0-9]{1,2}).*", "\\1", annoUpPeaks_AME_df$Comparison) # column to identify which timepoint is compared to Cycling or day 3 controls, by removing everything after day[0-9] where [0-9] is 1 or 2 digits in the Comparison column. 
annoUpPeaks_AME_df$Timepoint <- factor(annoUpPeaks_AME_df$Timepoint, levels=c("day3", "day10", "day14", "day21", "day28"))
```

# ATAC-seq: plot motif enrichment results in the AP1 family for ALL up peaks across all timepoints and drug treatments (DESeq comparisons)
```{r}
# load in function to generate matrix of -log10(padj) values of motif enrichment results
load("/lustre/fs4/risc_lab/scratch/jyeung/Manuscript_Figures/FigureS3/Functions/create_AME_peaks_matrix.RData")

# function to create dotplots for motif enrichment results for each DESeq comparison. 
create_AME_dotplots <- function(AME_df=AME_padj_dots, Title=Title, fill_limit=c(1,10), size_limit=4.5){
  AME_df <- AME_df %>% mutate(Comparison = Timepoint)
  ggplot(AME_df, aes(x=Comparison, y=motif_ID, size=TPvsFP)) +
    geom_point(aes(fill=neglog10padj), colour="black", pch=21, alpha=0.8) +
    scale_fill_gradient2(name="-log10(padj)", 
                        low="white", mid="light yellow", high="dark orange",
                        midpoint = 3,
                        limits=fill_limit) + # Adjust fill scale
    scale_size_continuous(name="%TP - %FP", 
                          limits=size_limit, 
                          range=c(1, 10)) +  # Adjust dot sizes
    theme_minimal() +
    ggtitle(Title) +
    scale_x_discrete(labels = function(x) AME_df$Timepoint[match(x, AME_df$Comparison)]) +  # to replace Comparison with Cluster labels on the x-axis. 
    facet_wrap(~Group, nrow=1, scales="free") +
    theme(
      axis.text.x = element_text(size=8, angle = 90, hjust=1),  # Rotate x-axis labels
      strip.text.x = element_text(size=8, face="bold"),
      strip.text.y = element_text(size=8, face="bold")
    )+
    theme_classic() +
    labs(x="Comparison", y="motif ID")}

AP1_UpPeaks_AME_mat <- create_AME_peaks_matrix(annoUpPeaks_AME_df[grepl("JUN|FOS|ATF", annoUpPeaks_AME_df$motif_ID), ])
                                                      
AP1_UpPeaks_AME_mat <- AP1_UpPeaks_AME_mat[order(rowSums(AP1_UpPeaks_AME_mat), decreasing=T), ] # order by overall most to least enriched AP1 motifs 

outdir <- "/lustre/fs4/risc_lab/scratch/jyeung/Manuscript_Figures/additional_AP1_figures"

# plot motif enrichment values of AP1 motifs in all Up peaks for all timepoints vs Cycling. 
pdf(paste0(outdir, "/ATAC_AP1_UpPeaks_AME_dotplots.pdf"), width=8, height=2.7)
create_AME_dotplots(annoUpPeaks_AME_df[grepl("JUN|FOS|ATF", annoUpPeaks_AME_df$motif_ID), ], Title="AP1 Motifs enriched in Up peaks", fill_limit=c(2, 305), size_limit=c(0, 51))
dev.off()
```